name: Deploy to kubernetes
on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/1054698923027/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'terraform-sa@mindbehind-407520.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Build and push docker image
      run: |
        gcloud auth activate-service-account terraform-sa@mindbehind-407520.iam.gserviceaccount.com --key-file="../terraform_k8s/mindbehind-407520-3d61d8bd05ba.json"
        gcloud auth configure-docker
        gcloud auth application-default login
        gcloud auth application-default set-quota-project mindbehind-407520
        gcloud auth list
        docker build -t gcr.io/mindbehind-407520/nodeappimage:$IMAGE_TAG .
        docker push gcr.io/mindbehind-407520/nodeappimage:$IMAGE_TAG
      working-directory: ./nodeapp
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      run: terraform init
      working-directory: ./terraform_cicd
    - name: Terraform Plan
      run: |
        terraform plan \
        -var="region=us-west1" \
        -var="project_id=mindbehind-407520" \
        -var="container_image=gcr.io/mindbehind-407520/nodeappimage:$IMAGE_TAG" \
        -out=PLAN
      working-directory: ./terraform_cicd
    - name: Terraform Apply
      run: terraform apply PLAN
      working-directory: ./terraform_cicd